# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation

name: Main workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-charts:
    uses: omec-project/.github/.github/workflows/lint-charts.yml@main
    secrets: inherit
    with:
      branch_name: ${{ github.ref }}

  license-check:
    uses: omec-project/.github/.github/workflows/license-check.yml@main
    with:
      branch_name: ${{ github.ref }}

  fossa-scan:
    uses: omec-project/.github/.github/workflows/fossa-scan.yml@main
    with:
      branch_name: ${{ github.ref }}
