# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation
on:
  push:
    branches:
      - main

jobs:
  tag-github:
    uses: omec-project/.github/.github/workflows/tag-github.yml@main
    secrets: inherit

  publish:
    uses: omec-project/.github/.github/workflows/publish-charts.yml@main
    secrets: inherit
    with:
      branch_name: ${{ github.ref }}

  update-version:
    needs: tag-github
    uses: omec-project/.github/.github/workflows/update-version.yml@main
    with:
      changed: ${{ needs.tag-github.outputs.changed }}
      version: ${{ needs.tag-github.outputs.version }}
    secrets: inherit
